using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TunicRandomizer {
    public class Hints {
        public static Dictionary<string, string> HintLocations = new Dictionary<string, string>() {
            {"Overworld Redux (-7.0, 12.0, -136.4)", "Mailbox"},
            {"Archipelagos Redux (-170.0, 11.0, 152.5)", "West Garden Relic"},
            {"Swamp Redux 2 (92.0, 7.0, 90.8)", "Swamp Relic"},
            {"Sword Access (28.5, 5.0, -190.0)", "East Forest Relic"},
            {"Library Hall (131.0, 19.0, -8.5)", "Library Relic"},
            {"Monastery (-6.0, 26.0, 180.5)", "Monastery Relic"},
            {"Fortress Reliquary (198.5, 5.0, -40.0)", "Fortress Relic"},
            {"Overworld Redux (89.0, 44.0, -107.0)", "East Forest Sign"},
            {"Overworld Redux (-5.0, 36.0, -70.0)", "Overworld Sign"},
            {"Overworld Redux (8.0, 20.0, -115.0)", "Swamp Sign"},
            {"Overworld Redux (-156.0, 12.0, -44.3)", "West Garden Sign"},
            {"Overworld Redux (73.0, 44.0, -38.0)", "Fortress Sign"},
            {"Overworld Redux (-141.0, 40.0, 34.8)", "Quarry Sign"},
            {"Temple (14.0, -0.5, 49.0)", "Temple Statue"}
        };

        public static Dictionary<string, string> HintMessages = new Dictionary<string, string>();

        public static Dictionary<string, string> SimplifiedSceneNames = new Dictionary<string, string>() {
            {"Cathedral Arena", "Gauntlet"},
            {"Furnace", "Overworld Belltower"},
            {"frog cave main", "Frog's Domain"},
            {"Overworld Redux", "Overworld"},
            {"CubeRoom", "Overworld"},
            {"Sword Cave", "Overworld"},
            {"EastFiligreeCache", "Overworld"},
            {"Overworld Cave", "Overworld"},
            {"Ruins Passage", "Overworld"},
            {"Forest Belltower", "Forest Belltower"},
            {"East Forest Redux", "East Forest"},
            {"Sword Access", "East Forest"},
            {"East Forest Redux Interior", "East Forest"},
            {"East Forest Redux Laddercave", "East Forest"},
            {"Fortress Courtyard", "Fortress Courtyard"},
            {"PatrolCave", "Patrol Cave"},
            {"Waterfall", "Secret Gathering Place"},
            {"Ruined Shop", "Ruined Shop"},
            {"Town_FiligreeRoom", "Overworld"},
            {"Changing Room", "Changing Room"},
            {"Town Basement", "Overworld"},
            {"Transit", "Far Shore"},
            {"Maze Room", "Overworld"},
            {"Atoll Redux", "Ruined Atoll"},
            {"Library Hall", "Library"},
            {"Library Lab", "Library"},
            {"Library Arena", "Library"},
            {"Overworld Interiors", "Old House"},
            {"Sewer", "Bottom of the Well"},
            {"Sewer_Boss", "Bottom of the Well"},
            {"Crypt Redux", "Dark Tomb"},
            {"Archipelagos Redux", "West Garden"},
            {"archipelagos_house", "West Garden"},
            {"Temple", "Sealed Temple"},
            {"Fortress Basement", "Beneath the Vault"},
            {"Fortress Main", "Eastern Vault"},
            {"Fortress Reliquary", "Fortress Courtyard"},
            {"Dusty", "Fortress Exterior"},
            {"Fortress East", "Eastern Vault"},
            {"Fortress Arena", "Siege Engine"},
            {"ShopSpecial", "Overworld"},
            {"Mountain", "Mountaintop"},
            {"Mountaintop", "Mountaintop"},
            {"Quarry Redux", "Quarry"},
            {"Monastery", "Monastery"},
            {"ziggurat2020_1", "Rooted Ziggurat"},
            {"ziggurat2020_2", "Rooted Ziggurat"},
            {"ziggurat2020_3", "Rooted Ziggurat"},
            {"Swamp Redux 2", "Swamp"},
            {"Cathedral Redux", "Cathedral"},
            {"RelicVoid", "Hero's Grave"},
            {"", "Trinket Well"}
        };

        public static Dictionary<string, string> SimplifiedItemNames = new Dictionary<string, string>() {
            {"Hyperdash", "Hero's Laurels"},
            {"Lantern", "Lantern"},
            {"Wand", "Magic Orb"},
            {"GoldenTrophy_9", "Golden Trophy"},
            {"CubeRoom-(321.1, 3.0, 217.0)", "Fairy"},
            {"Stick", "Stick"},
            {"Flask Shard", "Flask Shard"},
            {"Firecracker", "Firecracker"},
            {"Fool", "Fool"},
            {"GoldenTrophy_3", "Golden Trophy"},
            {"Key", "Key"},
            {"Pepper", "Pepper"},
            {"Piggybank L1", "Piggybank"},
            {"money", "Money"},
            {"Trinket - Glass Cannon", "Trinket Card"},
            {"Berry_MP", "MP Berry"},
            {"Overworld Cave-(-90.4, 515.0, -738.9)", "Fairy"},
            {"5", "Page"},
            {"GoldenTrophy_1", "Golden Trophy"},
            {"Overworld Redux-(90.4, 36.0, -122.1)", "Fairy"},
            {"14", "Page"},
            {"6", "Page"},
            {"Berry_HP", "HP Berry"},
            {"7", "Page"},
            {"Flask Container", "Flask"},
            {"East Forest Redux-(104.0, 16.0, 61.0)", "Fairy"},
            {"Sword", "Sword"},
            {"Firebomb", "Fire Bomb"},
            {"Ice Bomb", "Ice Bomb"},
            {"Trinket Coin", "Golden Coin"},
            {"East Forest Redux-(164.0, -25.0, -56.0)", "Fairy"},
            {"Upgrade Offering - Health HP - Flower", "HP Upgrade Flower"},
            {"GoldenTrophy_6", "Golden Trophy"},
            {"Upgrade Offering - PotionEfficiency Swig - Ash", "Potion Upgrade Ash"},
            {"Overworld Redux-(64.5, 44.0, -40.0)", "Fairy"},
            {"PatrolCave-(74.0, 46.0, 24.0)", "Fairy"},
            {"Techbow", "Fire Wand"},
            {"24", "Page"},
            {"Waterfall-(-47.0, 45.0, 10.0)", "Fairy"},
            {"Upgrade Offering - Attack - Tooth", "Attack Upgrade Tooth"},
            {"GoldenTrophy_8", "Golden Trophy"},
            {"8", "Page"},
            {"Overworld Redux-(-132.0, 28.0, -55.5)", "Fairy"},
            {"22", "Page"},
            {"21", "Page"},
            {"Overworld Redux-(-83.0, 20.0, -117.5)", "Fairy"},
            {"Trinket - Heartdrops", "Trinket Card"},
            {"Key (House)", "Old House Key"},
            {"Ivy", "Ivy"},
            {"Overworld Redux-(-52.0, 2.0, -174.8)", "Fairy"},
            {"GoldenTrophy_4", "Golden Trophy"},
            {"SlowmoItem", "Hourglass"},
            {"Town Basement-(-202.0, 28.0, 150.0)", "Fairy"},
            {"Bait", "Lure"},
            {"16", "Page"},
            {"1", "Page"},
            {"GoldenTrophy_12", "Golden Trophy"},
            {"Maze Room-(1.0, 0.0, -1.0)", "Fairy"},
            {"4", "Page"},
            {"Trinket - Block Plus", "Trinket Card"},
            {"Trinket - Bloodstain MP", "Trinket Card"},
            {"Upgrade Offering - Magic MP - Mushroom", "MP Upgrade Mushroom"},
            {"Trinket - IFrames", "Trinket Card"},
            {"Trinket - Attack Up Defense Down", "Trinket Card"},
            {"GoldenTrophy_10", "Golden Trophy"},
            {"Upgrade Offering - DamageResist - Effigy", "Defense Upgrade Effigy"},
            {"Library Hall-(133.3, 10.0, -43.2)", "Fairy"},
            {"20", "Page"},
            {"25", "Page"},
            {"19", "Page"},
            {"Hexagon Green", "Hexagon Green"},
            {"Overworld Interiors-(-28.0, 27.0, -50.5)", "Fairy"},
            {"Shield", "Shield"},
            {"26", "Page"},
            {"27", "Page"},
            {"2", "Page"},
            {"9", "Page"},
            {"17", "Page"},
            {"Trinket - Bloodstain Plus", "Trinket Card"},
            {"15", "Page"},
            {"Trinket - MP Flasks", "Trinket Card"},
            {"Trinket - RTSR", "Trinket Card"},
            {"Trinket - BTSR", "Trinket Card"},
            {"13", "Page"},
            {"Archipelagos Redux-(-396.3, 1.4, 42.3)", "Fairy"},
            {"Stundagger", "Ice Dagger"},
            {"23", "Page"},
            {"Upgrade Offering - Stamina SP - Feather", "SP Upgrade Feather"},
            {"Archipelagos Redux-(-236.0, 8.0, 86.3)", "Fairy"},
            {"Temple-(14.0, 0.1, 42.4)", "Fairy"},
            {"12", "Page"},
            {"3", "Page"},
            {"Trinket - Sneaky", "Trinket Card"},
            {"18", "Page"},
            {"Fortress Main-(-75.0, -1.0, 17.0)", "Fairy"},
            {"Trinket - Walk Speed Plus", "Trinket Card"},
            {"GoldenTrophy_11", "Golden Trophy"},
            {"Vault Key (Red)", "Vault Key"},
            {"Hexagon Red", "Hexagon Red"},
            {"11", "Page"},
            {"10", "Page"},
            {"0", "Page"},
            {"Quarry Redux-(0.7, 68.0, 84.7)", "Fairy"},
            {"Mask", "Trinket Card"},
            {"Shotgun", "Shotgun"},
            {"Trinket - Parry Window", "Trinket Card"},
            {"Hexagon Blue", "Hexagon Blue"},
            {"GoldenTrophy_7", "Golden Trophy"},
            {"Trinket - Fast Icedagger", "Trinket Card"},
            {"Trinket - Stamina Recharge Plus", "Trinket Card"},
            {"GoldenTrophy_5", "Golden Trophy"},
            {"GoldenTrophy_2", "Golden Trophy"},
            {"Trinket Slot", "Trinket Slot"},
            {"Relic - Hero Sword", "Hero Relic"},
            {"Relic - Hero Pendant MP", "Hero Relic"},
            {"Relic - Hero Water", "Hero Relic"},
            {"Relic - Hero Pendant HP", "Hero Relic"},
            {"Relic - Hero Crown", "Hero Relic"},
            {"Relic - Hero Pendant SP", "Hero Relic"}
        };

    }
}
